// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Traces.Data;

#nullable disable

namespace Traces.Migrations
{
    [DbContext(typeof(TracesDbContext))]
    [Migration("20260519133615_added_opencode_to_traces")]
    partial class added_opencode_to_traces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Traces.Data.Models.Trace", b =>
                {
                    b.Property<Guid>("TraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AxialCodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("OpenCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("TraceCollectionId")
                        .HasColumnType("uuid");

                    b.HasKey("TraceId");

                    b.HasIndex("TraceCollectionId");

                    b.ToTable("Traces");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceAttribute", b =>
                {
                    b.Property<Guid>("TraceId")
                        .HasColumnType("uuid");

                    b.Property<int>("TraceAttributeType")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TraceId", "TraceAttributeType", "Key");

                    b.ToTable("TraceAttributes");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceCollection", b =>
                {
                    b.Property<Guid>("TraceCollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ProjectVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("TraceCollectionId");

                    b.ToTable("TraceCollections");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceMessage", b =>
                {
                    b.Property<Guid>("TraceId")
                        .HasColumnType("uuid");

                    b.Property<int>("TraceMessageType")
                        .HasColumnType("integer");

                    b.Property<int>("Index")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TraceId", "TraceMessageType", "Index");

                    b.ToTable("TraceMessages");
                });

            modelBuilder.Entity("Traces.Data.Models.Trace", b =>
                {
                    b.HasOne("Traces.Data.Models.TraceCollection", "TraceCollection")
                        .WithMany("Traces")
                        .HasForeignKey("TraceCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TraceCollection");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceAttribute", b =>
                {
                    b.HasOne("Traces.Data.Models.Trace", "Trace")
                        .WithMany("TraceAttributes")
                        .HasForeignKey("TraceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trace");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceMessage", b =>
                {
                    b.HasOne("Traces.Data.Models.Trace", "Trace")
                        .WithMany("TraceMessages")
                        .HasForeignKey("TraceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trace");
                });

            modelBuilder.Entity("Traces.Data.Models.Trace", b =>
                {
                    b.Navigation("TraceAttributes");

                    b.Navigation("TraceMessages");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceCollection", b =>
                {
                    b.Navigation("Traces");
                });
#pragma warning restore 612, 618
        }
    }
}
