// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Traces.Data;

#nullable disable

namespace Traces.Migrations
{
    [DbContext(typeof(TracesDbContext))]
    [Migration("20260609122257_add_open_code")]
    partial class add_open_code
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Traces.Data.Models.SpanAttribute", b =>
                {
                    b.Property<Guid>("SpanId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("TraceAttributeType")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2560)
                        .HasColumnType("character varying(2560)");

                    b.HasKey("SpanId", "Key");

                    b.ToTable("SpanAttributes");
                });

            modelBuilder.Entity("Traces.Data.Models.SpanEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("SpanId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TimeUnixNano")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("EventId");

                    b.HasIndex("SpanId");

                    b.ToTable("SpanEvent");
                });

            modelBuilder.Entity("Traces.Data.Models.SpanEventAttribute", b =>
                {
                    b.Property<Guid>("SpanEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("TraceAttributeType")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2560)
                        .HasColumnType("character varying(2560)");

                    b.HasKey("SpanEventId", "Key");

                    b.ToTable("SpanEventAttributes");
                });

            modelBuilder.Entity("Traces.Data.Models.Trace", b =>
                {
                    b.Property<Guid>("TraceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("OpenCode")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("TraceCollectionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TraceGroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TraceGroupId1")
                        .HasColumnType("uuid");

                    b.HasKey("TraceId");

                    b.HasIndex("TraceCollectionId");

                    b.HasIndex("TraceGroupId");

                    b.HasIndex("TraceGroupId1");

                    b.ToTable("Traces");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceCollection", b =>
                {
                    b.Property<Guid>("TraceCollectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ProjectVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("TraceCollectionId");

                    b.ToTable("TraceCollections");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceGroup", b =>
                {
                    b.Property<Guid>("TraceGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("TraceGroupType")
                        .HasColumnType("integer");

                    b.HasKey("TraceGroupId");

                    b.ToTable("TraceGroups");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceResource", b =>
                {
                    b.Property<Guid>("TraceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TraceAttributeType")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(32768)
                        .HasColumnType("character varying(32768)");

                    b.HasKey("TraceId", "Key");

                    b.ToTable("TraceResources");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceScope", b =>
                {
                    b.Property<Guid>("TraceScopeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("TraceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(2560)
                        .HasColumnType("character varying(2560)");

                    b.HasKey("TraceScopeId");

                    b.HasIndex("TraceId");

                    b.ToTable("TraceScopes");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceScopeSpan", b =>
                {
                    b.Property<Guid>("TraceScopeSpanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("EndTimeUnixNano")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ParentSpanId")
                        .HasColumnType("uuid");

                    b.Property<int>("SpanKind")
                        .HasColumnType("integer");

                    b.Property<decimal>("StartTimeUnixNano")
                        .HasColumnType("numeric(20,0)");

                    b.Property<Guid>("TraceScopeId")
                        .HasColumnType("uuid");

                    b.HasKey("TraceScopeSpanId");

                    b.HasIndex("TraceScopeId");

                    b.ToTable("TraceScopeSpans");
                });

            modelBuilder.Entity("Traces.Data.Models.SpanAttribute", b =>
                {
                    b.HasOne("Traces.Data.Models.TraceScopeSpan", "TraceScopeSpan")
                        .WithMany("SpanAttributes")
                        .HasForeignKey("SpanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TraceScopeSpan");
                });

            modelBuilder.Entity("Traces.Data.Models.SpanEvent", b =>
                {
                    b.HasOne("Traces.Data.Models.TraceScopeSpan", "TraceScopeSpan")
                        .WithMany("SpanEvents")
                        .HasForeignKey("SpanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TraceScopeSpan");
                });

            modelBuilder.Entity("Traces.Data.Models.SpanEventAttribute", b =>
                {
                    b.HasOne("Traces.Data.Models.SpanEvent", "SpanEvent")
                        .WithMany("SpanEventAttributes")
                        .HasForeignKey("SpanEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpanEvent");
                });

            modelBuilder.Entity("Traces.Data.Models.Trace", b =>
                {
                    b.HasOne("Traces.Data.Models.TraceCollection", "TraceCollection")
                        .WithMany("Traces")
                        .HasForeignKey("TraceCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Traces.Data.Models.TraceGroup", null)
                        .WithMany("Traces")
                        .HasForeignKey("TraceGroupId");

                    b.HasOne("Traces.Data.Models.TraceGroup", "TraceGroup")
                        .WithMany()
                        .HasForeignKey("TraceGroupId1");

                    b.Navigation("TraceCollection");

                    b.Navigation("TraceGroup");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceResource", b =>
                {
                    b.HasOne("Traces.Data.Models.Trace", "Trace")
                        .WithMany("TraceResources")
                        .HasForeignKey("TraceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trace");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceScope", b =>
                {
                    b.HasOne("Traces.Data.Models.Trace", "Trace")
                        .WithMany("TraceScopes")
                        .HasForeignKey("TraceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trace");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceScopeSpan", b =>
                {
                    b.HasOne("Traces.Data.Models.TraceScope", "TraceScope")
                        .WithMany("TraceScopeSpans")
                        .HasForeignKey("TraceScopeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TraceScope");
                });

            modelBuilder.Entity("Traces.Data.Models.SpanEvent", b =>
                {
                    b.Navigation("SpanEventAttributes");
                });

            modelBuilder.Entity("Traces.Data.Models.Trace", b =>
                {
                    b.Navigation("TraceResources");

                    b.Navigation("TraceScopes");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceCollection", b =>
                {
                    b.Navigation("Traces");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceGroup", b =>
                {
                    b.Navigation("Traces");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceScope", b =>
                {
                    b.Navigation("TraceScopeSpans");
                });

            modelBuilder.Entity("Traces.Data.Models.TraceScopeSpan", b =>
                {
                    b.Navigation("SpanAttributes");

                    b.Navigation("SpanEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
