name: TestDbCompose

services:
  db:
    image: postgres:18
    container_name: TestDb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrator:
    build:
      context: .
      dockerfile: MigrationRunner/Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__Default=Host=db;Port=5432;Database=mydb;Username=user;Password=${POSTGRES_PASSWORD}
    restart: on-failure

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gui2
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD:-admin}
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
