# Build stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY . .
RUN dotnet publish Shared/Shared.csproj -c Release -o /app/publish && \
    dotnet publish Traces/Traces.csproj -c Release -o /app/publish && \
    dotnet publish Projects/Projects.csproj -c Release -o /app/publish && \
    dotnet publish ProjectVersions/ProjectVersions.csproj -c Release -o /app/publish && \
    dotnet publish Api/Api.csproj -c Release -o /app/publish

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Api.dll"]
