// <auto-generated />
using System;
using JudgeTemplates.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JudgeTemplates.Migrations
{
    [DbContext(typeof(JudgeTemplatesDbContext))]
    partial class JudgeTemplatesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JudgeTemplates.Data.Models.JudgeTemplate", b =>
                {
                    b.Property<Guid>("JudgeTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AxialCodeId")
                        .HasColumnType("uuid");

                    b.Property<int?>("CurrentVersionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("CustomJudgeTemplateContent")
                        .HasMaxLength(2147483647)
                        .HasColumnType("text");

                    b.Property<bool>("IsDeprecated")
                        .HasColumnType("boolean");

                    b.Property<string>("JudgeTemplateDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("JudgeTemplateName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProjectVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("JudgeTemplateId");

                    b.ToTable("JudgeTemplates");
                });

            modelBuilder.Entity("JudgeTemplates.Data.Models.JudgeTemplateVersion", b =>
                {
                    b.Property<Guid>("JudgeTemplateVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JudgeTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("JudgeTemplateVersionId");

                    b.HasIndex("JudgeTemplateId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("JudgeTemplateVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
