<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AssessmentCriteria\AssessmentCriteria.csproj" />
    <ProjectReference Include="..\AxialCodes.Contracts\AxialCodes.Contracts.csproj" />
    <ProjectReference Include="..\AxialCodes\AxialCodes.csproj" />
    <ProjectReference Include="..\JudgeTemplates\JudgeTemplates.csproj" />
    <ProjectReference Include="..\Projects\Projects.csproj" />
    <ProjectReference Include="..\Settings\Settings.csproj" />
    <ProjectReference Include="..\ProjectVersions\ProjectVersions.csproj" />
    <ProjectReference Include="..\Statistics\Statistics.csproj" />
    <ProjectReference Include="..\Traces\Traces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Mediator.SourceGenerator" Version="3.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.5" />
    <PackageReference Include="Scriban" Version="7.0.0" PrivateAssets="all" />
  </ItemGroup>
</Project>
