// <auto-generated />
using System;
using AxialCodes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AxialCodes.Migrations
{
    [DbContext(typeof(AxialCodeDbContext))]
    partial class AxialCodeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AxialCodes.Data.Models.AxialCode", b =>
                {
                    b.Property<Guid>("AxialCodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AxialCodingResultId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.PrimitiveCollection<Guid[]>("TraceIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("AxialCodeId");

                    b.HasIndex("AxialCodingResultId");

                    b.ToTable("AxialCode");
                });

            modelBuilder.Entity("AxialCodes.Data.Models.AxialCodingResult", b =>
                {
                    b.Property<Guid>("AxialCodingResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProjectVersionId")
                        .HasColumnType("uuid");

                    b.HasKey("AxialCodingResultId");

                    b.HasIndex("ProjectVersionId", "IsActive")
                        .IsUnique()
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("AxialCodingResults");
                });

            modelBuilder.Entity("AxialCodes.Data.Models.AxialCode", b =>
                {
                    b.HasOne("AxialCodes.Data.Models.AxialCodingResult", "AxialCodingResult")
                        .WithMany("AxialCodes")
                        .HasForeignKey("AxialCodingResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AxialCodingResult");
                });

            modelBuilder.Entity("AxialCodes.Data.Models.AxialCodingResult", b =>
                {
                    b.Navigation("AxialCodes");
                });
#pragma warning restore 612, 618
        }
    }
}
