<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Statistics</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AxialCodes.Contracts\AxialCodes.Contracts.csproj" />
    <ProjectReference Include="..\Projects.Contracts\Projects.Contracts.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
    <ProjectReference Include="..\Traces.Contracts\Traces.Contracts.csproj" />
  </ItemGroup>
</Project>
